### ISSUE TITLE
not workin :(

### ISSUE THREAD

**Issue by mstrolo** [WizzardSK/gameflix#1] opened 2023-09-27 19:55 UTC
Hi.

i have installed it on Betocera Linux 

it worked great for 2 days.

after restarting all of a sudden its not trying to load the games.

any idea what should I do?

**Comment by WizzardSK** [comment] 2023-09-28 06:49
Hi, thank you for testing my simple project. Could you please add more information? Which version of Batocera, x86 or arm64? Have you tried to restart Batocera? Have you made some Batocera upgrade? Can you see any roms in roms folder? Thanks!

**Comment by mstrolo** [comment] 2023-09-28 18:34
hI.

First of all thank you for this its amazing...
version:  batocera-x86_64-37-20230617.img
I didn't upgrade or did any update or such.

i see all the roms in the roms folder I think... there are a lot of folders.


I am saying again it worked and stopped working for some reason

**Comment by WizzardSK** [comment] 2023-09-28 19:07
Ok, so I see that roms seem to be mounted and they are just not starting. I assume you made a few restarts and the problem persists. Which platform are you using? Have you tried another platform? These bugs are hard to debug, but it would help to give some log from batocera if there is some. You may also connect to discord and we may discuss it live https://discord.gg/aJsVfUr6CA

edit: I checked it yesterday and today and it works for me, so better connect to that discord channel to discuss

**Comment by WizzardSK** [comment] 2023-10-02 08:30
Please add more information so I can find out where is the problem. Otherwise I should close the issue as not reproduced. Feel free to connect to our discord and discuss there.

**Comment by WizzardSK** [comment] 2023-10-04 17:48
closed because no other info was provided

**Closed as not planned** 2023-10-04 17:48 UTC
